<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="RestAPI"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="0.024">
    <properties></properties>

            <testcase
                name="test_post"
                time="0.024"
                classname="TestNG.PAC1">

            <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void TestNG.PAC1.test_post(java.lang.String,java.lang.String,int)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: test_post([java.lang.String arg0, java.lang.String arg1, int arg2])
Arguments: [(java.lang.String) Govinda,(java.lang.String) Lakshmi,(java.lang.String) 2]">
                <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void TestNG.PAC1.test_post(java.lang.String,java.lang.String,int)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: test_post([java.lang.String arg0, java.lang.String arg1, int arg2])
Arguments: [(java.lang.String) Govinda,(java.lang.String) Lakshmi,(java.lang.String) 2]
                org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)org.testng.internal.Parameters.injectParameters(Parameters.java:918)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)java.base/java.util.ArrayList.forEach(ArrayList.java:1511)org.testng.TestRunner.privateRun(TestRunner.java:819)org.testng.TestRunner.run(TestRunner.java:619)org.testng.SuiteRunner.runTest(SuiteRunner.java:443)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)org.testng.SuiteRunner.run(SuiteRunner.java:336)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)org.testng.TestNG.runSuitesLocally(TestNG.java:1228)org.testng.TestNG.runSuites(TestNG.java:1134)org.testng.TestNG.run(TestNG.java:1101)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </failure>
    </testcase>


</testsuite>
